default_agent: customer_support_agent
agents:
  customer_support_agent:
    name: customer_support_agent
    language: python
    node_version: '20'
    entrypoint: C:/Users/KushalBhargav/OneDrive - Systech Solutions, Inc/udacity/project_2/cd14763-project-starter/starter/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\KushalBhargav\OneDrive - Systech Solutions, Inc\udacity\project_2\cd14763-project-starter\starter
    aws:
      execution_role: arn:aws:iam::084942134421:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-aa96c3a063
      execution_role_auto_create: false
      account: 084942134421
      region: us-east-1
      ecr_repository: 084942134421.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-customer_support_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: customer_support_agent-WOlrNpFLIt
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:084942134421:runtime/customer_support_agent-WOlrNpFLIt
      agent_session_id: browser-test-session-20260927-TEST2
    codebuild:
      project_name: bedrock-agentcore-customer_support_agent-builder
      execution_role: arn:aws:iam::084942134421:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-aa96c3a063
      source_bucket: bedrock-agentcore-codebuild-sources-084942134421-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: customer_support_agent_mem-CmxKdFFuBC
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:084942134421:memory/customer_support_agent_mem-CmxKdFFuBC
      memory_name: customer_support_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
